name: Deploy Vite app to GitHub Pages (TensorFlow版 安定構成)

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ① ソース取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # ② Node.js 18 + npm 9 を明示的にセットアップ
      - name: Setup Node.js (use npm 9 for stability)
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      # ③ npmを強制的に9系にダウングレード
      - name: Downgrade npm to v9
        run: npm install -g npm@9

      # ④ 依存パッケージをインストール
      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund

      # ⑤ Viteでビルド
      - name: Build project
        run: npm run build

      # ⑥ GitHub Pagesへデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
