name: Deploy Backend to Render

on:
  push:
    branches:
      - master  # masterブランチにpushされたとき動く

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./server  # サーバーコードの場所を指定

      - name: Run tests
        run: npm test
        working-directory: ./server

      - name: Deploy to Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_TOKEN" \
          -d '{"serviceId": "あなたのRenderサービスID"}' \
          https://api.render.com/v1/services/あなたのRenderサービスID/deploys
